FROM golang:1.22-alpine

# Install Ruby and development tools for testing
RUN apk --no-cache add ruby ruby-dev build-base ruby-json tzdata ca-certificates

# Install required Ruby gems
RUN gem install icalendar minitest

WORKDIR /app

# Copy source code
COPY . .

# Build the application
RUN go build -o bin/ical_merger ./cmd

# Set the default command for testing
CMD ["make", "test-all"]