version: '3'

services:
  ical_merger:
    build: .
    container_name: ical_merger
    command: ["/app/ical_merger", "-serve"]
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
      - ./output:/app/output
    environment:
      - OUTPUT_TIMEZONE=${OUTPUT_TIMEZONE:-Europe/Berlin}
    restart: unless-stopped